{% set version = "0.0.7" %}

package:
  name: nanobind
  version: {{ version }}

source:
  url: https://github.com/wjakob/nanobind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65e8305a9f1e291b9ac1ce3129828737c486f24aefeb1e220e5e252062c56709

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  requires:
    - python >=3.8
    - pip
  commands:
    - pip check
    - python -c "import nanobind; import os; assert os.path.isdir(nanobind.cmake_dir()) and os.path.isdir(nanobind.include_dir())"

about:
  home: https://github.com/wjakob/nanobind
  summary: Seamless operability between C++17 and Python
  description: |
    nanobind is a small binding library that exposes C++ types in Python and
    vice versa. It is reminiscent of Boost.Python and pybind11 and uses
    near-identical syntax. In contrast to these existing tools, nanobind is
    more efficient: bindings compile in a shorter amount of time, producing
    smaller binaries with better runtime performance.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wjakob/nanobind

extra:
  recipe-maintainers:
    - MatthiasKohl
    - wjakob
