{% set name = "nanobind" %}
{% set version = "2.12.0" %}
{% set abi_version = 19 %}
{% set robin_map_commit = "188c45569cc2a5dd768077c193830b51d33a5020" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 0ae77c1a88f27153fa57045ee00f7b0a7b06b1cd3df942e95a34b38c5d0a5bee
  - url: https://github.com/Tessil/robin-map/archive/{{ robin_map_commit }}.tar.gz
    sha256: 2f4be670fa4f53c3261ed7af392b414a00e75591f87da0a8dd525de376430747
    folder: ext/robin_map

build:
  number: 1

outputs:
  - name: nanobind-abi
    version: {{ abi_version }}
    build:
      run_exports:
        - nanobind-abi =={{ abi_version }}
    test:
      source_files:
        - src/nb_abi.h
      commands:
        # make sure the internals version matches the package version
        - if [[ $(grep "define NB_INTERNALS_VERSION" src/nb_abi.h | grep -E -o '[0-9]+') != "{{ abi_version }}" ]]; then exit 1; fi  # [not win]
        - powershell -Command "if ((Select-String -Path src\nb_abi.h -Pattern 'define NB_INTERNALS_VERSION').Line -match '(\d+)' -and $matches[1] -ne '{{abi_version}}') { exit 1 }"  # [win]
  - name: nanobind
    script: build_nanobind.sh  # [not win]
    script: bld_nanobind.bat  # [win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - cmake
        - make  # [not win]
        - scikit-build-core >=0.10
      run:
        - python
      run_constrained:
        - nanobind-abi =={{ abi_version }}
    # The pytests are disabled. _ext files missed. Example:
    # test_chrono_ext -> https://github.com/wjakob/nanobind/blob/v2.5.0/tests/test_chrono.py#L3
    test:
      imports:
        - nanobind
      commands:
        - pip check
        - python -c "import nanobind; import os; assert os.path.isdir(nanobind.cmake_dir()) and os.path.isdir(nanobind.include_dir())"
      requires:
        - pip
        - pytest

about:
  home: https://github.com/wjakob/nanobind
  summary: Seamless operability between C++17 and Python
  description: |
    nanobind is a small binding library that exposes C++ types in Python and
    vice versa. It is reminiscent of Boost.Python and pybind11 and uses
    near-identical syntax. In contrast to these existing tools, nanobind is
    more efficient: bindings compile in a shorter amount of time, producing
    smaller binaries with better runtime performance.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - ext/robin_map/LICENSE
  doc_url: https://github.com/wjakob/nanobind/tree/master/docs
  dev_url: https://github.com/wjakob/nanobind

extra:
  recipe-maintainers:
    - snegireff
  skip-lints:
    - missing_imports_or_run_test_py
    - missing_wheel
    - missing_python
    - missing_section
    - missing_python_build_tool
    - missing_pip_check
