{% set name = "nanobind" %}
{% set version = "2.5.0" %}
{% set abi_version = 15 %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc8412e94acffa20a369191382bcdbb6fbfb302e475e87cacff9516d51023a15
  patches:  # [osx]
    # TODO: Need to remove the patch after conda updates the linker to a version higher than 609.
    # Support for response files was added in ld64 609:
    # https://github.com/tpoechtrager/cctools-port/commit/86cf74fd50016550703435302c33c17474759666
    - patches/0001-fix-undefined-symbols-on-osx.patch  # [osx]

build:
  number: 1

outputs:
  - name: nanobind-abi
    version: {{ abi_version }}
    build:
      noarch: generic
      run_exports:
        - nanobind-abi =={{ abi_version }}
    test:
      source_files:
        - src/nb_internals.cpp
      commands:
        # make sure the internals version matches the package version
        # https://github.com/wjakob/nanobind/blob/v2.5.0/src/nb_internals.cpp#L21
        - if [ $(grep "define NB_INTERNALS_VERSION" src/nb_internals.cpp | grep -E -o '[0-9]+') != "{{ abi_version }}" ]; then exit 1; fi  # [not win]
        - powershell -Command "if ((Select-String -Path src\nb_internals.cpp -Pattern 'define NB_INTERNALS_VERSION').Line -match '(\d+)' -and $matches[1] -ne '{{abi_version}}') { exit 1 }"  # [win]

  - name: nanobind
    script: build_nanobind.sh  # [not win]
    script: bld_nanobind.bat  # [win]
    requirements:
      build:
        - patch  # [osx]
        - cmake
        - make  # [linux]
      host:
        - pip
        - python
        - wheel
        - setuptools
        - scikit-build-core >=0.10
      run:
        - python
      run_constrained:
        - nanobind-abi =={{ abi_version }}
    # The pytests are disabled. _ext files missed. Example:
    # test_chrono_ext -> https://github.com/wjakob/nanobind/blob/v2.5.0/tests/test_chrono.py#L3
    test:
      imports:
        - nanobind
      commands:
        - pip check
        - python -c "import nanobind; import os; assert os.path.isdir(nanobind.cmake_dir()) and os.path.isdir(nanobind.include_dir())"
      requires:
        - pip
        - pytest

about:
  home: https://github.com/wjakob/nanobind
  summary: Seamless operability between C++17 and Python
  description: |
    nanobind is a small binding library that exposes C++ types in Python and
    vice versa. It is reminiscent of Boost.Python and pybind11 and uses
    near-identical syntax. In contrast to these existing tools, nanobind is
    more efficient: bindings compile in a shorter amount of time, producing
    smaller binaries with better runtime performance.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - ext/robin_map/LICENSE
  doc_url: https://github.com/wjakob/nanobind/tree/master/docs
  dev_url: https://github.com/wjakob/nanobind

extra:
  recipe-maintainers:
    - snegireff
  skip-lints:
    - missing_imports_or_run_test_py
    - missing_wheel
    - missing_python
    - missing_section
    - missing_python_build_tool
    - missing_pip_check
